DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS artists;

CREATE TABLE artists(
  id SERIAL8 PRIMARY KEY,
  artist_name VARCHAR(255) NOT NULL
);

CREATE TABLE albums(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  artist_id INT8 REFERENCES artists(id) --ON DELETE CASCADE???
);
